# Generated by Django 2.0.2 on 2018-04-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='miniature',
            field=models.ImageField(blank=True, null=True, upload_to='api/diary/miniature/'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='miniature',
            field=models.ImageField(blank=True, null=True, upload_to='api/entry/miniature/'),
        ),
    ]
